// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acmmprdmuydsuywensbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbW1wcmRtdXlkc3V5d2Vuc2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNDc1MjgsImV4cCI6MjA1MTcyMzUyOH0.afFxnnmMzGGDHrGPZ7zbwesdtqHuLZpxYx-bUq6BVnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);